blank_issues_enabled: false
contact_links:
  - name: Pull Request Templates
    url: https://github.com/hoyoungleee/sub_Practice/tree/main/.github/PULL_REQUEST_TEMPLATE
    about: PR 작성 시 사용할 템플릿을 선택하세요.
